---
iframe: http://some/url/that/will/be/at/the/bottom
sources:
    -
        type: JIRA
        args:
            name: jira
            client:
                - 'https://bugs.startsiden.no'
                - 'builder'
                - 'password'
            custom_fields:
                project: 10070
                team: 10520
#    -
#        type: iCal
#        args:
#            name: operations
#            ics_url: 'http://some/ics/file'
    -
        type: BlockedDays
        args:
            name: blocked

view:
    TT:
        template:
                INCLUDE_PATH:
                    - "__path_to(templates)__"
                DEFAULT_ENCODING: 'utf-8'
                WRAPPER: 'inc/wrap.tt'
                PRE_PROCESS: 'inc/preprocess.tt'
db:
    dsn: 'MongoDB:database_name=jirastatus;database_host=mongodb;collection_name=events'
    #dsn: 'dbi:SQLite:dbname=/home/andreas/systems/jira-status/foo'#
