version: '2'
services:
    mongodb:
        image: sameersbn/mongodb:latest
        ports:
            - "27017:27017"
        volumes:
            - ./db:/var/lib/mongodb
        restart: always
    server:
        build:
            context: .
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
    app:
        build:
            context: .
        command: ./bin/jira-status store_events
        depends_on:
            - mongodb

